version: "3.7"
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    ports:
      - "9000:9000"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-enabled
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    build:
      context: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1 # 自己輸入伺服器 IP
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3000:80"
    depends_on:
      - mysql
