version: "3.7"
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    ports:
      - "9000:9000"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-enabled
    ports:
      - "80:80"
    depends_on:
      - php-fpm
