version: "3.7"
services:
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - VERSION=${PHP_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    ports:
      - "9000:9000"
  laravel-echo-server:
    build:
      context: ./laravel-echo-server
    ports:
      - "6001:6001"
  nginx:
    build:
      context: ./nginx
      args:
        - VERSION=${NGINX_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-enabled
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - laravel-echo-server
  mysql:
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    build:
      context: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1 # 自己輸入伺服器 IP
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3000:80"
    depends_on:
      - mysql
  workspace:
    build:
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    tty: true
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
