version: "3.7"
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
services:
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - VERSION=${PHP_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    ports:
      - "9000:9000"
    networks:
      - backend
  php-worker:
    build:
      context: ./php-worker
      args:
        - VERSION=${PHP_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ${PHP_WORKER_LOG_PATH}:/var/log/supervisor
      - ${PHP_WORKER_CONF_PATH}:/etc/supervisord.d
    ports:
      - "9001:9001"
    networks:
      - backend
  laravel-echo-server:
    build:
      context: ./laravel-echo-server
    ports:
      - "6001:6001"
    networks:
      - frontend
      - backend
  nginx:
    build:
      context: ./nginx
      args:
        - VERSION=${NGINX_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-enabled
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - laravel-echo-server
    networks:
      frontend:
      backend:
        aliases:
          # Laravel echo server 與 Laravel 互 call 需要
          - ${OUTGOING_DOMAIN}
          - ${OUTGOING_WEBSOCKET_DOMAIN}
  mysql:
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
  phpmyadmin:
    build:
      context: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1 # 自己輸入伺服器 IP
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3000:80"
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
  workspace:
    build:
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    tty: true
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - frontend
      - backend
